name: batch
description: A lightweight and powerful batch library written in Dart. You can easily develop a job schedule and batch program in Dart with this library.
version: 0.2.1
homepage: https://github.com/myConsciousness/batch.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cron: ^0.4.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  import_sorter: ^4.6.0
