name: batch
description: A lightweight and powerful batch library written in Dart.
version: 0.0.1
homepage: https://github.com/myConsciousness/batch.dart

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cron: ^0.4.0


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
