name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check release validity
        run: sh .github/scripts/check-release.sh
      - name: Tweet
        uses: snow-actions/tweet@v1.1.2
        with:
          status: |
            Released new version (${{ github.event.release.name }}) of Batch.dart!🐦🐦🐦
            Release note: ${{ github.event.release.html_url }}

            This tweet was sent from GitHub Actions workflow at https://github.com/batch-dart/batch.dart
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
